### ISSUE TITLE
[Question] how to get the cover image for each episode in the feed to work

### ISSUE THREAD

**Issue by ganar** [podigee/podigee-quickplay#6]
I have this feed that I've been trying to publish using the *Podigee Player* and generating the individual chapters configurations using this script. I can't get the covers for each episode to work: What should I add either to my feed or to the configuration (and how) to make it work. I'm using the script that you are running on https://quickplay.podigee.com/

This is my feed. http://querrecuentos.3ph.com/rss/sound.xml 

The only cover image I get is the one that the podcast use 

Any help on the subject is deeply appreciated

**Comment by benzimmer** [comment]
You need to have an `<itunes:image>` entry referencing the cover image for each episode in the feed.

**Comment by ganar** [comment]
Hello @benzimmer 

I added all of the `<itunes:image>` tags in each of the episodes of the feed, but still the system show the wrong image, and or no image at all. there seems to be a problem with both a cache in https://quickplay.podigee.com/ and the mixing of `https` and `http` resources (I don't have a valid certificate in my server, and Itunes fail with the lets encrypt certificates)

What should I do in this case? Any help is appreciated.

**Comment by benzimmer** [comment]
The image loads fine for me but there was a problem with the media file. It had a mime-type specified the app was not expecting. I fixed that and also cleared the caches. Let me know if it works for you!

**Comment by ganar** [comment]
Now the script configuration does reference the images correctly. I hope that the player will show the images because it will be running in the same URL where both the RSS and the images are stored.

Thanks a lot @benzimmer: I would not have been able to solve this alone.

**Comment by benzimmer** [comment]
It should work fine if both, the site and the images are served via http.

Btw.: iTunes accepts Letsencrypt certificates for quite some time now: https://feed.press/blog/2016/12/16/apple-silently-adds-support-lets-encrypt-certificates-podcast-feeds/
